In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [2]:
# check Pillow version number
import PIL
print('Pillow Version:', PIL.__version__)

Pillow Version: 7.2.0


In [3]:
from PIL import Image
from numpy import asarray
# load the image
image = Image.open('IMG_20150125_111213.jpg')
# convert image to numpy array
data = asarray(image)
# summarize shape
print(data.shape)
# create Pillow image
image2 = Image.fromarray(data)
# summarize image details
print(image2.format)
print(image2.mode)
print(image2.size)



(2160, 3840, 3)
None
RGB
(3840, 2160)


In [4]:
import cv2
from os import listdir
from matplotlib import image
# load all images in a directory
positive_images = list()
for filename in listdir('kohli'):
    #newsize=(64,64)
    im1= Image.open('kohli/' + filename)
    #print(im1)
    #im1=im1.resize(newsize)
    im1 = im1.resize((64,64), Image.ANTIALIAS)
    im1 = asarray(im1)
   # im1= im1.(f + ' resized.jpg', 'JPEG', quality=90)
    positive_images.append(im1)
    print('> loaded %s %s' % (filename, im1.shape))
    
print(len(positive_images))

> loaded 088db66e0b.jpg (64, 64, 3)
> loaded 1146943f73.jpg (64, 64, 3)
> loaded 132a62a742.jpg (64, 64, 3)
> loaded 150fc612d2.jpg (64, 64, 3)
> loaded 2018439965.jpg (64, 64, 3)
> loaded 266f9eacf3.jpg (64, 64, 3)
> loaded 27ad99a806.jpg (64, 64, 3)
> loaded 28e155755b.jpg (64, 64, 3)
> loaded 357f957b72.jpg (64, 64, 3)
> loaded 37d3f53e84.jpg (64, 64, 3)
> loaded 3846bffc28.jpg (64, 64, 3)
> loaded 39c2bd6fc9.jpg (64, 64, 3)
> loaded 39e1dd840f.jpg (64, 64, 3)
> loaded 41de91b30f.jpg (64, 64, 3)
> loaded 47f53ee402.jpg (64, 64, 3)
> loaded 49f7355f97.jpg (64, 64, 3)
> loaded 5181ba2b71.jpg (64, 64, 3)
> loaded 52345a338c.jpg (64, 64, 3)
> loaded 549e5c755e.jpg (64, 64, 3)
> loaded 55620911db.jpg (64, 64, 3)
> loaded 59a89ee258.jpg (64, 64, 3)
> loaded 5e51e39db9.jpg (64, 64, 3)
> loaded 631e46db26.jpg (64, 64, 3)
> loaded 632b7bb5ea.jpg (64, 64, 3)
> loaded 644558382a.jpg (64, 64, 3)
> loaded 688be3f972.jpg (64, 64, 3)
> loaded 71ed3d75ae.jpg (64, 64, 3)
> loaded 76a06a6ec1.jpg (64,

In [5]:
negative_images = list()
for filename in listdir('-images'):
    #newsize=(64,64)
    im1= Image.open('-images/' + filename)
    #print(im1)
    #im1=im1.resize(newsize)
    im1 = im1.resize((64,64), Image.ANTIALIAS)
    im1 = asarray(im1)
   # im1= im1.(f + ' resized.jpg', 'JPEG', quality=90)
    negative_images.append(im1)
    print('> loaded %s %s' % (filename, im1.shape))
print(len(negative_images))

> loaded 001aa018f83f14d5a9cd30.jpg (64, 64, 3)
> loaded 0043bd6fa9f01d43d601a5ff47ce21dc.jpg (64, 64, 3)
> loaded 004bce1989034b6f362beecff5300996.jpg (64, 64, 3)
> loaded 04df8682cad2996946d006e4a49643e0.jpg (64, 64, 3)
> loaded 055ebbda79d7f58f5ff895030c2945ec.jpg (64, 64, 3)
> loaded 0a0df79221b794470d2e416986ca812d.jpg (64, 64, 3)
> loaded 0da088875998ec122f89650f8402b6cc.jpg (64, 64, 3)
> loaded 1.jpg (64, 64, 3)
> loaded 1474100286733.jpg (64, 64, 3)
> loaded 1474100287346.jpg (64, 64, 3)
> loaded 166-1666011_maria-sharapova-wallpaper-hd-tennis-maria-sharapova-4k.jpg (64, 64, 3)
> loaded 1708306.jpg (64, 64, 3)
> loaded 1807072.jpg (64, 64, 3)
> loaded 1807073.jpg (64, 64, 3)
> loaded 1807074.jpg (64, 64, 3)
> loaded 1807077.jpg (64, 64, 3)
> loaded 1807078.jpg (64, 64, 3)
> loaded 1807081.jpg (64, 64, 3)
> loaded 1807086.jpg (64, 64, 3)
> loaded 1807089.jpg (64, 64, 3)
> loaded 1807094.jpg (64, 64, 3)
> loaded 1e151b33efea81a11235aa4572055d9a.jpg (64, 64, 3)
> loaded 1ed72a806c

In [6]:
len(negative_images)

76

In [7]:
type(negative_images)

list

In [8]:
negative_array=np.array(negative_images)
positive_array=np.array(positive_images)

In [9]:
print(negative_array.shape)
print(positive_array.shape)

(76, 64, 64, 3)
(82, 64, 64, 3)


In [10]:
type(negative_array)

numpy.ndarray

In [11]:
negative_array

array([[[[156, 207, 243],
         [156, 207, 244],
         [157, 207, 244],
         ...,
         [169, 219, 255],
         [169, 219, 254],
         [168, 220, 254]],

        [[152, 206, 242],
         [153, 206, 243],
         [155, 207, 242],
         ...,
         [165, 218, 254],
         [165, 218, 254],
         [165, 218, 255]],

        [[151, 206, 241],
         [153, 206, 243],
         [156, 207, 242],
         ...,
         [170, 218, 252],
         [169, 219, 253],
         [167, 219, 253]],

        ...,

        [[ 37,  64,  91],
         [ 29,  58,  83],
         [ 31,  59,  86],
         ...,
         [ 11,  14,   9],
         [ 10,  13,   6],
         [ 10,  13,   7]],

        [[ 37,  65,  92],
         [ 78, 101, 121],
         [ 85, 107, 127],
         ...,
         [ 11,  14,   9],
         [ 12,  15,  10],
         [ 10,  13,   6]],

        [[ 34,  63,  90],
         [ 88, 110, 130],
         [ 97, 117, 135],
         ...,
         [ 13,  17,   8],
        

In [12]:
positive_array

array([[[[ 85, 202, 167],
         [ 90, 207, 172],
         [111, 190, 169],
         ...,
         [ 99, 107, 113],
         [100, 103, 112],
         [ 94,  97, 106]],

        [[ 64, 198, 159],
         [110, 212, 179],
         [132, 216, 190],
         ...,
         [107, 116, 122],
         [107, 110, 119],
         [ 95,  97, 108]],

        [[108, 210, 183],
         [143, 222, 194],
         [143, 224, 199],
         ...,
         [115, 124, 130],
         [113, 116, 125],
         [ 95,  96, 108]],

        ...,

        [[220, 221, 169],
         [ 61, 188, 135],
         [ 72, 199, 155],
         ...,
         [241, 242, 243],
         [236, 240, 245],
         [218, 229, 238]],

        [[189, 205, 166],
         [ 24, 181, 130],
         [ 85, 201, 145],
         ...,
         [242, 244, 245],
         [235, 239, 244],
         [217, 228, 238]],

        [[157, 200, 171],
         [  6, 174, 130],
         [110, 199, 137],
         ...,
         [245, 249, 249],
        

In [13]:
plt.imshow(positive_array[1])

In [14]:
i = 0; j = 0; k = 0
n1=positive_array.shape[0]
n2=negative_array.shape[0]
training_data=np.zeros((n1+n2,64,64,3))
    # Traverse both array 
while (i < n1 and j < n2) : 
    training_data[k] = positive_array[i] 
    i += 1
    k += 1
          
    training_data[k] = negative_array[j] 
    j += 1
    k += 1
      
  
    # Store remaining elements of first array 
while (i < n1) : 
    training_data[k] = positive_array[i] 
    i += 1
    k += 1
  
    # Store remaining elements of second array 
while (j < n2) : 
    training_data[k] = negative_array[j] 
    k += 1
    j += 1
        

In [15]:
print(training_data)

[[[[ 85. 202. 167.]
   [ 90. 207. 172.]
   [111. 190. 169.]
   ...
   [ 99. 107. 113.]
   [100. 103. 112.]
   [ 94.  97. 106.]]

  [[ 64. 198. 159.]
   [110. 212. 179.]
   [132. 216. 190.]
   ...
   [107. 116. 122.]
   [107. 110. 119.]
   [ 95.  97. 108.]]

  [[108. 210. 183.]
   [143. 222. 194.]
   [143. 224. 199.]
   ...
   [115. 124. 130.]
   [113. 116. 125.]
   [ 95.  96. 108.]]

  ...

  [[220. 221. 169.]
   [ 61. 188. 135.]
   [ 72. 199. 155.]
   ...
   [241. 242. 243.]
   [236. 240. 245.]
   [218. 229. 238.]]

  [[189. 205. 166.]
   [ 24. 181. 130.]
   [ 85. 201. 145.]
   ...
   [242. 244. 245.]
   [235. 239. 244.]
   [217. 228. 238.]]

  [[157. 200. 171.]
   [  6. 174. 130.]
   [110. 199. 137.]
   ...
   [245. 249. 249.]
   [232. 237. 241.]
   [215. 226. 237.]]]


 [[[156. 207. 243.]
   [156. 207. 244.]
   [157. 207. 244.]
   ...
   [169. 219. 255.]
   [169. 219. 254.]
   [168. 220. 254.]]

  [[152. 206. 242.]
   [153. 206. 243.]
   [155. 207. 242.]
   ...
   [165. 218. 254.]
 

In [16]:
training_data.shape

(158, 64, 64, 3)

In [17]:
b=np.zeros((1,n2))
a=np.ones((1,n1))
print(len(a[0]),len(b[0]))

82 76


In [18]:
i = 0; j = 0; k = 0
n1=a.shape[1]
n2=b.shape[1]
train_y=np.zeros((1,n1+n2))


    # Traverse both array 
while (i < n1 and j < n2) : 
    train_y[0,k] = a[0,i] 
    
    i += 1
    k += 1
          
    train_y[0,k] = b[0,j] 
    
    j += 1
    k += 1
    
  
    # Store remaining elements of first array 
while (i < n1) : 
    train_y[0,k] = a[0,i] 
    i += 1
    k += 1
  
    # Store remaining elements of second array 
while (j < n2) : 
    train_y[0,k] = b[0,j] 
    k += 1
    j += 1

In [19]:
train_y.shape

(1, 158)

In [20]:
train_y

array([[1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
        1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
        1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
        1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
        1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
        1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
        1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
        1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
        1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
        1., 0., 1., 0., 1., 0., 1., 0., 1., 1., 1., 1., 1., 1.]])

In [21]:
# Reshape the training examples
train_x_flatten = training_data.reshape(training_data.shape[0], -1).T   # The "-1" makes reshape flatten the remaining dimensions


# Standardize data to have feature values between 0 and 1.
train_x = train_x_flatten/255.


print ("train_x's shape: " + str(train_x.shape))



train_x's shape: (12288, 158)


In [22]:
def sigmoid(Z):
    
    
    A = 1/(1+np.exp(-Z))
    cache = Z
    
    return A, cache





def relu(Z):
  
    
    A = np.maximum(0,Z)
    
    assert(A.shape == Z.shape)
    
    cache = Z 
    return A, cache





def relu_backward(dA, cache):

    
    Z = cache
    dZ = np.array(dA, copy=True) # just converting dz to a correct object.
    
    # When z <= 0, you should set dz to 0 as well. 
    dZ[Z <= 0] = 0
    
    assert (dZ.shape == Z.shape)
    
    return dZ





def sigmoid_backward(dA, cache):

    
    Z = cache
    
    s = 1/(1+np.exp(-Z))
    dZ = dA * s * (1-s)
    
    assert (dZ.shape == Z.shape)
    
    return dZ

In [23]:


def linear_forward(A, W, b):

    
    
    p=W.shape
    q=A.shape
    r=b.shape
    #print(p)
    #print(q)
    #print(r)
    #print(b)
    if(b.shape[1]!=1):
        b=b[0,:]
        b=b.reshape((b.shape[0],1))
    
    Z = np.dot(W,A) + b
    
    
    assert(Z.shape == (W.shape[0], A.shape[1]))
    cache = (A, W, b)
    
    return Z, cache,p,q


In [24]:


def linear_activation_forward(A_prev, W, b, activation):
    
    
    if activation == "sigmoid":
        # Inputs: "A_prev, W, b". Outputs: "A, activation_cache".
        
        Z, linear_cache,p,q = linear_forward(A_prev, W, b)
        A, activation_cache = sigmoid(Z)
        
    
    elif activation == "relu":
        # Inputs: "A_prev, W, b". Outputs: "A, activation_cache".
        
        Z, linear_cache,p,q = linear_forward(A_prev, W, b)
        A, activation_cache = relu(Z)
        
    
    assert (A.shape == (W.shape[0], A_prev.shape[1]))
    cache = (linear_cache, activation_cache)

    return A, cache,p,q

In [25]:


def compute_cost(AL, Y):

    
    m = Y.shape[1]

    # Compute loss from aL and y.
    
    cost = (-1 / m) * np.sum(np.multiply(Y, np.log(AL)) + np.multiply(1 - Y, np.log(1 - AL)))
    
    
    cost = np.squeeze(cost)      # To make sure your cost's shape is what we expect (e.g. this turns [[17]] into 17).
    assert(cost.shape == ())
    
    return cost

In [26]:


def linear_backward(dZ, cache):

    A_prev, W, b = cache
    m = A_prev.shape[1]

    
    dW = np.dot(dZ, cache[0].T) / m
    db = np.squeeze(np.sum(dZ, axis=1, keepdims=True)) / m
    dA_prev = np.dot(cache[1].T, dZ)
    
    
    assert (dA_prev.shape == A_prev.shape)
    assert (dW.shape == W.shape)
    #assert (isinstance(db, float))
    p=type(db)
    return dA_prev, dW, db


In [27]:


def update_parameters(parameters, grads, learning_rate):

    
    L = len(parameters) // 2 # number of layers in the neural network

    # Update rule for each parameter. Use a for loop.
    
    for l in range(L):
        parameters["W" + str(l + 1)] = parameters["W" + str(l + 1)] - learning_rate * grads["dW" + str(l + 1)]
        parameters["b" + str(l + 1)] = parameters["b" + str(l + 1)] - learning_rate * grads["db" + str(l + 1)]
    
        
    return parameters

In [28]:


def initialize_parameters_deep(layer_dims):
 
    
    np.random.seed(3)
    parameters = {}
    L = len(layer_dims)            # number of layers in the network

    for l in range(1, L):
       
        parameters['W' + str(l)] = np.random.randn(layer_dims[l], layer_dims[l - 1]) * 0.01
        parameters['b' + str(l)] = np.zeros((layer_dims[l], 1))
        
        
        assert(parameters['W' + str(l)].shape == (layer_dims[l], layer_dims[l - 1]))
        assert(parameters['b' + str(l)].shape == (layer_dims[l], 1))

        
    return parameters









def L_model_forward(X, parameters):
  

    caches = []
    A = X
    L = len(parameters) // 2                  # number of layers in the neural network
    
    # Implement [LINEAR -> RELU]*(L-1). Add "cache" to the "caches" list.
    for l in range(1, L):
        A_prev = A 
        
        A, cache,p1,q1 = linear_activation_forward(A_prev, 
                                             parameters['W' + str(l)], 
                                             parameters['b' + str(l)], 
                                             activation='relu')
        caches.append(cache)
        
        
    
    # Implement LINEAR -> SIGMOID. Add "cache" to the "caches" list.
   
    AL, cache,p,q = linear_activation_forward(A, 
                                          parameters['W' + str(L)], 
                                          parameters['b' + str(L)], 
                                          activation='sigmoid')
    caches.append(cache)
    

    
    assert(AL.shape == (1, X.shape[1]))
            
    return AL, caches,p,q









def L_model_backward(AL, Y, caches):
 
    grads = {}
    L = len(caches) # the number of layers
    m = AL.shape[1]
    Y = Y.reshape(AL.shape) # after this line, Y is the same shape as AL
    
    # Initializing the backpropagation
    
    dAL = dAL = - (np.divide(Y, AL) - np.divide(1 - Y, 1 - AL))
    
    
    # Lth layer (SIGMOID -> LINEAR) gradients. Inputs: "AL, Y, caches". Outputs: "grads["dAL"], grads["dWL"], grads["dbL"]
   
    current_cache = caches[-1]
    grads["dA" + str(L)], grads["dW" + str(L)], grads["db" + str(L)] = linear_backward(sigmoid_backward(dAL, 
                                                                                                        current_cache[1]), 
                                                                                       current_cache[0])
    
    
    for l in reversed(range(L-1)):
        # lth layer: (RELU -> LINEAR) gradients.
        # Inputs: "grads["dA" + str(l + 2)], caches". Outputs: "grads["dA" + str(l + 1)] , grads["dW" + str(l + 1)] , grads["db" + str(l + 1)] 
        
        current_cache = caches[l]
        dA_prev_temp, dW_temp, db_temp = linear_backward(sigmoid_backward(dAL, current_cache[1]), current_cache[0])
        grads["dA" + str(l + 1)] = dA_prev_temp
        grads["dW" + str(l + 1)] = dW_temp
        grads["db" + str(l + 1)] = db_temp
       

    return grads



In [29]:
### CONSTANTS ###
layers_dims = [12288,20, 1] #  2-layer model

In [30]:


def L_layer_model(X, Y, layers_dims, learning_rate = 0.0075, num_iterations=101, print_cost=False):
  

    np.random.seed(1)
    costs = []                         # keep track of cost
    
    # Parameters initialization. (≈ 1 line of code)
    
    parameters = initialize_parameters_deep(layers_dims)
   
    
    # Loop (gradient descent)
    for i in range(0, num_iterations):

        # Forward propagation: [LINEAR -> RELU]*(L-1) -> LINEAR -> SIGMOID.
        
        AL, caches,p,q = L_model_forward(X, parameters)
        #print(p)
        #print(q)
        
        
        # Compute cost.
       
        cost = compute_cost(AL, Y)
        
    
        # Backward propagation.
        
        grads = L_model_backward(AL, Y, caches)
        
 
        # Update parameters.
        
        parameters = update_parameters(parameters, grads, learning_rate)
        
                
        # Print the cost every 100 iterations
        if print_cost and i % 100 == 0:
            print ("Cost after iteration %i: %f" %(i, cost))
        if print_cost and i % 100 == 0:
            costs.append(cost)
            
    # plot the cost
    plt.plot(np.squeeze(costs))
    plt.ylabel('cost')
    plt.xlabel('iterations')
    plt.title("Learning rate =" + str(learning_rate))
    plt.show()
    
    return parameters

In [31]:
parameters = L_layer_model(train_x, train_y, layers_dims, num_iterations = 700, print_cost = True)
print(parameters)

Cost after iteration 0: 0.693476
Cost after iteration 100: 0.463227
Cost after iteration 200: 0.383551
Cost after iteration 300: 0.335231
Cost after iteration 400: 0.290174
Cost after iteration 500: 0.257254
Cost after iteration 600: 0.230538


{'W1': array([[ 0.01882936,  0.00698667,  0.00493398, ...,  0.01747438,
         0.01970743, -0.00493756],
       [-0.02361014, -0.01505807, -0.00732213, ..., -0.01545294,
         0.0164779 ,  0.02467814],
       [ 0.00792039,  0.01363544, -0.00175273, ...,  0.00271858,
         0.0263044 ,  0.01443567],
       ...,
       [-0.00032061,  0.01092785, -0.01031846, ..., -0.01657174,
         0.01485288,  0.01897148],
       [ 0.00387049,  0.01835908,  0.01191085, ...,  0.00953977,
         0.0077521 ,  0.02848685],
       [ 0.00741745,  0.00335314,  0.00016388, ...,  0.00764601,
         0.00885127,  0.00564402]]), 'b1': array([[-0.01631072, -0.01628889, -0.01305073, -0.01764897, -0.0171579 ,
        -0.01801421, -0.01896449, -0.01561829, -0.01606695, -0.01758138,
        -0.01806262, -0.01837056, -0.01921898, -0.01718796, -0.02001455,
        -0.01825106, -0.01720925, -0.01682798, -0.0144846 , -0.01749408],
       [-0.01631072, -0.01628889, -0.01305073, -0.01764897, -0.0171579 ,
       

In [32]:
def predict(X, y, parameters):
    
    
    m = X.shape[1]
    n = len(parameters) // 2 # number of layers in the neural network
    p = np.zeros((1,m))
    
    # Forward propagation
    probas, caches,t,q = L_model_forward(X, parameters)

    
    # convert probas to 0/1 predictions
    for i in range(0, probas.shape[1]):
        if probas[0,i] > 0.5:
            p[0,i] = 1
        else:
            p[0,i] = 0
    
    #print results
    #print ("predictions: " + str(p))
    #print ("true labels: " + str(y))
    print("Accuracy: "  + str(np.sum((p == y)/m)))
        
    return p

In [33]:
pred_train= predict(train_x, train_y, parameters)

Accuracy: 0.9810126582278482


In [34]:
test_images = list()
for filename in listdir('+imgtest'):
    #newsize=(64,64)
    im1= Image.open('+imgtest/' + filename)
    #print(im1)
    #im1=im1.resize(newsize)
    im1 = im1.resize((64,64), Image.ANTIALIAS)
    im1 = asarray(im1)
   # im1= im1.(f + ' resized.jpg', 'JPEG', quality=90)
    test_images.append(im1)
    print('> loaded %s %s' % (filename, im1.shape))
print(len(test_images))

> loaded 02fa06cf94.jpg (64, 64, 3)
> loaded 05b9bac90a.jpg (64, 64, 3)
> loaded 0b43460429.jpg (64, 64, 3)
> loaded 0b53cce8c6.jpg (64, 64, 3)
> loaded 0eb2230fbf.jpg (64, 64, 3)
> loaded 1fee075645.jpg (64, 64, 3)
> loaded 2c06edccfb.jpg (64, 64, 3)
> loaded 3e6d62bc8e.jpg (64, 64, 3)
> loaded 3f5fd4fead.jpg (64, 64, 3)
> loaded 4cbef36ff6.jpg (64, 64, 3)
> loaded 5a3384f779.jpg (64, 64, 3)
> loaded 6a1a57040d.jpg (64, 64, 3)
> loaded 6adbc1218c.jpg (64, 64, 3)
> loaded 6ca67cbf33.jpg (64, 64, 3)
> loaded 6fb5b64053.jpg (64, 64, 3)
> loaded 7e224dbc5c.jpg (64, 64, 3)
> loaded 7fde5779f6.jpg (64, 64, 3)
> loaded 9a7668efc5.jpg (64, 64, 3)
> loaded 9bb09002ef.jpg (64, 64, 3)
> loaded 9c2340c897.jpg (64, 64, 3)
> loaded 9c64bc0211.jpg (64, 64, 3)
> loaded 9e30af3e8d.jpg (64, 64, 3)
22


In [35]:
for filename in listdir('-imgtest'):
    #newsize=(64,64)
    im1= Image.open('-imgtest/' + filename)
    #print(im1)
    #im1=im1.resize(newsize)
    im1 = im1.resize((64,64), Image.ANTIALIAS)
    im1 = asarray(im1)
   # im1= im1.(f + ' resized.jpg', 'JPEG', quality=90)
    test_images.append(im1)
    print('> loaded %s %s' % (filename, im1.shape))
print(len(test_images))

> loaded 05a6581aba1e5e73530de513ffb05c70.jpg (64, 64, 3)
> loaded 05b889eaf7f5a4139a0485b8d6569307.jpg (64, 64, 3)
> loaded 26ED6CF600000578-3008031-image-a-105_1427131595123.jpg (64, 64, 3)
> loaded 36c7f74c8ca299e38ff9d887bebff942.jpg (64, 64, 3)
> loaded 36d4eca9-ab64-4f9f-bc82-5568ab9742ec-sharapova.jpg (64, 64, 3)
> loaded 37a5714882971bfae652f211fcb45dda.jpg (64, 64, 3)
> loaded 5b911f522806b0b92c20dbff32c3ab5f.jpg (64, 64, 3)
> loaded 5bd946a6cdbadfc416e59db42422c06c.jpg (64, 64, 3)
> loaded 5cb62e40230000c2006db3ac.jpg (64, 64, 3)
> loaded 5d028b68f1a62ccaea80ed6ff15994a1.jpg (64, 64, 3)
> loaded 5de5fed30f25441e5823254c.jpg (64, 64, 3)
> loaded 5e4bac9b3b62b77617608663.jfif (64, 64, 3)
> loaded 5e6c172ade99333d6ec3911da916f6ff.jpg (64, 64, 3)
> loaded 5ec0d7ffb3fc42ef4aac1b26c1eead17.jpg (64, 64, 3)
> loaded 6d409ff04b719c7822905a0198a8218b.jpg (64, 64, 3)
> loaded 6e43df5e0bd94e6f1355586eb5bd1ad5--picture-poses-akshay-kumar.jpg (64, 64, 3)
> loaded 7c2545e422999ec106d3f1b381

In [36]:
test_array=np.array(test_images)
test_array
print(test_array)

[[[[ 83  86  66]
   [ 60  64  48]
   [ 36  41  29]
   ...
   [125 120  99]
   [123 119  96]
   [123 118  95]]

  [[ 61  64  47]
   [ 48  52  37]
   [ 33  37  26]
   ...
   [128 124  98]
   [128 124  97]
   [128 124  97]]

  [[ 46  48  34]
   [ 41  44  30]
   [ 31  34  25]
   ...
   [125 121  95]
   [127 123  97]
   [129 125 100]]

  ...

  [[254 113 156]
   [238  98 138]
   [164  68  97]
   ...
   [ 30  58  85]
   [ 30  57  84]
   [ 29  56  83]]

  [[252 107 150]
   [236  93 133]
   [178  71 103]
   ...
   [ 31  59  89]
   [ 30  59  88]
   [ 30  58  88]]

  [[248  99 138]
   [230  89 126]
   [174  72 101]
   ...
   [ 30  59  91]
   [ 29  59  88]
   [ 29  58  88]]]


 [[[ 38  36 133]
   [ 39  37 134]
   [ 40  38 135]
   ...
   [110  78 145]
   [110  78 145]
   [109  77 139]]

  [[ 50  48 145]
   [ 50  48 145]
   [ 49  47 144]
   ...
   [109  77 144]
   [109  77 144]
   [107  76 138]]

  [[ 52  50 147]
   [ 52  50 147]
   [ 54  52 149]
   ...
   [108  76 143]
   [108  76 143]
   [107  75

In [37]:
test_x=test_array
test_y=np.zeros((1,42))
for i in range(22):
    test_y[0][i]=1

print(test_x.shape)
print(test_y.shape)
print(test_y)

(42, 64, 64, 3)
(1, 42)
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [38]:
# Reshape the test examples 
test_x_flatten = test_x.reshape(test_x.shape[0], -1).T   # The "-1" makes reshape flatten the remaining dimensions


# Standardize data to have feature values between 0 and 1.
test_x = test_x_flatten/255.


print ("test_x's shape: " + str(test_x.shape))

test_x's shape: (12288, 42)


In [39]:
pred_test = predict(test_x, test_y, parameters)

Accuracy: 0.7619047619047619


In [40]:
import anvil.server
from keras.preprocessing.image import load_img
from keras.preprocessing.image import img_to_array
from keras.preprocessing.image import array_to_img

In [41]:
anvil.server.connect('OZGKMAT7PF4KUJXX6V7Y3D53-NAWX4USSGJATQA3Y')

Connecting to wss://anvil.works/uplink
Anvil websocket open
Connected to "Default environment (dev)" as SERVER


In [42]:
import anvil.media
@anvil.server.callable
def classify_image(file):
    with anvil.media.TempFile(file) as filename:
        img= load_img(filename)
    img=img.resize((64,64), Image.ANTIALIAS)
    arr = asarray(img)
    
    arr=np.array(arr)
    arr=arr.astype(np.float32)
    arr = arr.reshape(12288,1)
    #arr=img_to_array(img)
    #arr=np.expand_dims(arr,axis=0)
    arr/=255.0
    
    probas, caches,t,q = L_model_forward(arr, parameters)
    return ('Person Detected' if probas>0.60 else 'Person does not Detected',float(probas))

In [43]:
# # Code developed by Dirk Colbry
# # This code snipit tries to read from your computer's camera.  It is not fully tested so it may not work for everyone.

# from IPython.display import HTML

# main_text = """
# <video id="video" width="320" height="240" autoplay></video>
# <button id="snap">Snap Photo</button>
# <canvas id="canvas" width="320" height="240"></canvas>

# <script>
# // Grab elements, create settings, etc.
# var video = document.getElementById('video');

# // Get access to the camera!
# if(navigator.mediaDevices && navigator.mediaDevices.getUserMedia) {
#     // Not adding `{ audio: true }` since we only want video now
#     navigator.mediaDevices.getUserMedia({ video: true }).then(function(stream) {
#         //video.src = window.URL.createObjectURL(stream);
#         //video.play();
#         video.srcObject=stream;
#         video.play();
#     });
# }

# // Elements for taking the snapshot
# var canvas = document.getElementById('canvas');
# var context = canvas.getContext('2d');
# var video = document.getElementById('video');

# // Trigger photo take
# document.getElementById("snap").addEventListener("click", function() {
# 	context.drawImage(video, 0, 0, 320, 240);
#     var myCanvas = document.getElementById('canvas');
#     var image = myCanvas.toDataURL("image/png");
#     IPython.notebook.kernel.execute("print('testing')")
#     IPython.notebook.kernel.execute("image = '" + image + "'")
# });
# </script>

# """
# HTML(main_text)

# # from PIL import Image
# # import base64
# # import io

# # pil_im = Image.open(io.BytesIO(base64.b64decode(image.split(',')[1])))
# # %matplotlib inline
# # import matplotlib.pylab as plt
# # import numpy as np

# # img=pil_im.resize((64,64), Image.ANTIALIAS)
# # arr = asarray(img)
  
# # arr=np.array(arr)
# # arr=arr.astype(np.float32)
# # arr=np.delete(arr, 3, axis=2)
# # #print(arr.shape)
# # arr = arr.reshape(12288,1)
# # #arr=img_to_array(img)
# # #arr=np.expand_dims(arr,axis=0)
# # arr/=255.0
# # probas, caches,t,q = L_model_forward(arr, parameters)
# # print(probas)
# # if probas>0.7:
# #     print("Person Identified!!!")
# # else: print("Person does not identified")

In [44]:
# from PIL import Image
# import base64
# import io

# pil_im = Image.open(io.BytesIO(base64.b64decode(image.split(',')[1])))
# #pil_im
# %matplotlib inline
# import matplotlib.pylab as plt
# import numpy as np

# img=pil_im.resize((64,64), Image.ANTIALIAS)
# arr = asarray(img)
  
# arr=np.array(arr)
# arr=arr.astype(np.float32)
# arr=np.delete(arr, 3, axis=2)
# #print(arr.shape)
# arr = arr.reshape(12288,1)
# #arr=img_to_array(img)
# #arr=np.expand_dims(arr,axis=0)
# arr/=255.0
# probas, caches,t,q = L_model_forward(arr, parameters)
# print(probas)
# if probas>0.7:
#     print("Person Identified!!!")
# else: print("Person does not identified")

In [45]:
# %matplotlib inline
# import matplotlib.pylab as plt
# import numpy as np

# img=pil_im.resize((64,64), Image.ANTIALIAS)
# arr = asarray(img)
  
# arr=np.array(arr)
# arr=arr.astype(np.float32)
# arr=np.delete(arr, 3, axis=2)
# #print(arr.shape)
# arr = arr.reshape(12288,1)
# #arr=img_to_array(img)
# #arr=np.expand_dims(arr,axis=0)
# arr/=255.0
# probas, caches,t,q = L_model_forward(arr, parameters)
# print(probas)
# if probas>0.7:
#     print("Person Identified!!!")
# else: print("Person does not identified")